project:
  type: website
  output-dir: docs

website:
  title: "Jordan Revol"
  # site-url: "https://jrevol.com"
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: pages/projects.qmd
        text: Projects
      - href: pages/papers.qmd 
        text: Papers
      - href: pages/talks.qmd 
        text: Talks

format:
  html:
    embed-resources: false
    theme: cosmo
    css: www/styles.css
    toc: false

resources: 
  - "www/talks/*.pdf"
  - "www/publications/*.pdf"

